### PR TITLE
#510 Fixed import statements and added default exports

### LINKED ISSUE #510: adjust imports to use default exports when these are identical in value
## Context

With #187 we have the default exports added. Now update the usage as well.

### PR DESCRIPTION
**Pull request by ayushkatoch98**
# The Pull Request is ready

- [x] fixes #510
- [x] all actions are passing
- [x] only fixes a single issue

## Overview

Fixed import statements and added default export statement wherever necessary.

Test Summary before making changes 
image

Test Summary after making changes 
image

## Framework

- [x ] the change breaks no interface
- [x] default behaviour did not change
- [ ] any new text output is added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] documentation has been adjusted (if required)
- [ ] shared code has been extracted in a different file

### CODE REVIEW

File: framework/src/worker/runner.ts [hunk 1]
```diff
@@ -1,15 +1,11 @@
-import {
-  Result,
-} from '../result.js';
+import Result from '../result.js';
 import {
   request,
 } from 'needle';
 import {
```
Comment (Idrinth) [inline framework/src/worker/runner.ts:5]: I believe this is also a single export

**Review by Idrinth — CHANGES_REQUESTED** [review]
Just a tiny overlooked case, otherwise perfect!
