### PR TITLE
fix(framework): wrong type intersection in multi-reporter

### LINKED ISSUE #514: multi-reporter has a wront type intersection
## Context

In TypeScript, intersections are used to combine multiple types into a single one. An intersection type is represented using the ampersand symbol &. It allows you to combine multiple types into a single type that includes all the properties and methods from each type, thus creating more flexible and powerful type definitions.

However, some of the basic types of TypeScript should not be used with intersections:

- The never type represents the type of values that never occur. Intersecting any type with never will always result in type never.
-  The any type allows to opt-out of type checking during compilation. Expressions of type any allow you to access arbitrary properties, even ones that don’t exist. any comes at the cost of losing type safety, which is one of the main motivations for using TypeScript. Avoid using any when not necessary. Intersecting any type with any will always result in type any.
-  The undefined and null types are the types for their respective value. Intersecting any type with them will always result in type never.
-  The void type implies the absence of a type. Intersecting any type with void will always result in type never.

Additionally, an intersection with a type without members (for example, {}) doesn’t change the resulting type, is redundant, and can be safely removed from the intersection.

## Project

File: framework/src/reporter/multi-reporter.ts:9
sonar: https://sonarcloud.io/project/issues?open=AY3BCwwQON117fWgsitg&id=Idrinth_api-bench

### PR DESCRIPTION
**Pull request by owais34**
Addressed sonar cloud bug , indicating wrong type intersection in  framework/src/reporter/multi-reporter.ts:9

Closes #514

# The Pull Request is ready

- [x] fixes #514 
- [x] all actions are passing
- [x] only fixes a single issue

## Overview

Introduced a new local interface MultiReporterType which extends ReporterList & Reporter , this will replace the existing intersection type.
This will help sove the sonar issue https://sonarcloud.io/project/issues?open=AY3BCwwQON117fWgsitg&id=Idrinth_api-bench&tab=code

## Review points

Need review on the new interface/type name.

## Framework

- [x] the change breaks no interface
- [x] default behaviour did not change
- [ ] any new text output is added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] documentation has been adjusted (if required)
- [ ] shared code has been extracted in a different file

### CODE REVIEW

**Comment by Idrinth** [comment]
great, thank you!

File: framework/src/reporter/multi-reporter.ts [hunk 1]
```diff
@@ -5,8 +5,11 @@ interface ReporterList {
   addReporter: (reporter: Reporter) => void;
 }
 
+interface MultiReporterType extends ReporterList, Reporter {
```
Comment (Idrinth) [inline framework/src/reporter/multi-reporter.ts:8]: please extract that into a separate file, just for cleanliness

**Review by Idrinth — CHANGES_REQUESTED** [review]

File: framework/src/reporter/multi-reporter.ts (hunk 1 above)
Comment (owais34) [reply framework/src/reporter/multi-reporter.ts]: Refactored as desired.
